"""empty message

Revision ID: db6e59063f4a
Revises: 5e35da3ac028
Create Date: 2026-01-22 04:34:23.960863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db6e59063f4a'
down_revision: Union[str, Sequence[str], None] = '5e35da3ac028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=True)
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=True)
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    # ### end Alembic commands ###
